// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: monitor/v1/monitor.proto

package monitortypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

var File_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x18monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\"\t\n" +
	"\aServiceBKZIgithub.com/ejsadiarin/coregateway/internal/domain/monitor/v1;monitortypesb\x06proto3"

var (
	file_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_monitor_v1_monitor_proto_rawDescData []byte
)

func file_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_monitor_v1_monitor_proto_rawDescData
}

var file_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_monitor_v1_monitor_proto_goTypes = []any{
	(*Service)(nil), // 0: monitor.v1.Service
}
var file_monitor_v1_monitor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_monitor_v1_monitor_proto_init() }
func file_monitor_v1_monitor_proto_init() {
	if File_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_v1_monitor_proto_rawDesc), len(file_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_v1_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_monitor_v1_monitor_proto = out.File
	file_monitor_v1_monitor_proto_goTypes = nil
	file_monitor_v1_monitor_proto_depIdxs = nil
}
