syntax = "proto3";
package user.v1;
option go_package = "github.com/ejsadiarin/coregateway/internal/domain/user/v1;usertypes";

message User {
  string id = 1;
  string email = 2;
  string role = 3;
  string created_at = 4;
  string updated_at = 5;
}

message CreateUserRequest {
  string email = 1;
  string password = 2;
  string role = 3;
}

message UpdateUserRequest {
  string email = 1;
  string password = 2;
  string role = 3;
}

message UserResponse {
  string id = 1;
  string email = 2;
  string role = 3;
}
